# Generated by Django 4.0.4 on 2022-04-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('I', 'Informational'), ('S', 'Social'), ('E', 'Exorcism Attempt')], default='I', max_length=1)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.doll')),
            ],
        ),
    ]
