# Generated by Django 4.0.4 on 2022-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_doll_haunted_alter_seance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talisman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='seance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='doll',
            name='haunted',
            field=models.CharField(choices=[('True', True), ('False', False)], default=('True', True), max_length=5),
        ),
    ]
