# Generated by Django 4.0.4 on 2022-04-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_talisman_alter_seance_options_alter_doll_haunted'),
    ]

    operations = [
        migrations.AddField(
            model_name='doll',
            name='talismans',
            field=models.ManyToManyField(to='main_app.talisman'),
        ),
    ]
